files:
  - filename: id_ed25519
    content_file: "{{ ansible_env.HOME }}/github.com/dotfiles/ssh/encrypted_id_ed25519"
    mode: '0600'
  - filename: id_ed25519.pub
    content_file: "{{ ansible_env.HOME }}/github.com/dotfiles/ssh/id_ed25519.pub"
    mode: '0644'