---
- name: Setup dotfiles and SSH keys
  hosts: localhost
  become: no

  vars:
    dotfiles_repo: "https://github.com/yaustn/dotfiles.git"
    dotfiles_dest: "{{ ansible_env.HOME }}/github.com/dotfiles"
    ssh_dir: "{{ ansible_env.HOME }}/.ssh_test"
    encrypted_ssh_key_file: "{{ dotfiles_dest }}/ansible/files.yml"

  tasks:
    - name: Clone/Pull dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dest }}"
        update: yes
        version: master 
      tags:
        - dotfiles

    - name: Ensure .ssh directory exists
      file:
        path: "{{ ssh_dir }}"
        state: directory
        mode: '0700'
      tags:
        - ssh
        - dotfiles

    - name: Decrypt SSH keys file
      ansible.builtin.include_vars:
        file: "{{ encrypted_ssh_key_file }}"
        name: ssh_keys
      no_log: true  
      tags:
        - ssh
        - dotfiles

    - name: Copy SSH keys
      copy:
        content: "{{ lookup('file', item.content_file) }}"
        dest: "{{ ssh_dir }}/{{ item.filename }}"
        mode: "{{ item.mode | default('0600') }}"
      loop: "{{ ssh_keys.files }}"
      #no_log: true
      tags:
        - ssh
        - dotfiles

    - name: Generate public key from private key
      command: ssh-keygen -y -f {{ ssh_dir }}/id_ed25519
      register: pubkey_content
      changed_when: false  

    - name: Write public key to file
      copy:
        content: "{{ pubkey_content.stdout }} {{ ssh_key.comment | default('') }}"
        dest: "{{ ssh_dir }}/id_ed25519.pub"
        mode: '0644'

    # - name: Create symlinks for dotfiles
    #   file:
    #     src: "{{ dotfiles_dest }}/{{ item }}"
    #     dest: "{{ ansible_env.HOME }}/.{{ item }}"
    #     state: link
    #   loop:
    #     - bashrc
    #     - vimrc
    #     - gitconfig
        # Add more dotfiles as needed 