---
- name: Setup dotfiles and SSH keys
  hosts: localhost
  become: no

  vars:
    dotfiles_repo: "https://github.com/yaustn/dotfiles.git"
    dotfiles_dir: "{{ ansible_env.HOME }}/github.com/dotfiles"
    ssh_dir: "{{ ansible_env.HOME }}/.ssh"
    ssh_files: "{{ dotfiles_dir }}/ansible/ssh_files.yml"

  tasks:
    - name: Clone/Pull dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"
        update: yes
        version: master 
      ignore_errors: yes
      tags:
        - dotfiles

    - name: Ensure .ssh directory exists
      become_user: root
      file:
        path: "{{ ssh_dir }}"
        state: directory
        mode: '0700'
      tags:
        - ssh
        - dotfiles

    - name: Decrypt SSH keys file
      ansible.builtin.include_vars:
        file: "{{ ssh_files }}"
        name: ssh_keys
      no_log: true  
      tags:
        - ssh
        - dotfiles

    # - name: Copy SSH keys
    #   copy:
    #     content: "{{ lookup('file', item.content_file) }}"
    #     dest: "{{ ssh_dir }}/{{ item.filename }}"
    #     mode: "{{ item.mode | default('0600') }}"
    #   loop: "{{ ssh_keys.files }}"
    #   no_log: true
    #   tags:
    #     - ssh
    #     - dotfiles

    - name: Copy SSH config file
      copy:
        src: "{{ dotfiles_dir }}/ssh/config"
        dest: "{{ ssh_dir }}/config"
        mode: '0600'
      no_log: true
      tags:
        - ssh
        - dotfiles

    - name: Set authorized ssh key from file
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "{{ ansible_env.HOME }}/.ssh/*.pub"
      tags:
        - ssh
        - dotfiles

    - name: Copy Git configuration files to home directory
      copy:
        src: "{{ dotfiles_dir }}/git/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        mode: '0644'
      loop:
        - gitconfig
        - gitignore
      tags:
        - git
        - dotfiles
    
    - name: Copy VSCode settings
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/{{ item | basename }}"
        mode: '0644'
      loop: 
        - "{{ dotfiles_dir }}/vscode/settings.json"
        - "{{ dotfiles_dir }}/vscode/keybindings.json"
      tags:
        - vscode
        - dotfiles