---
- name: Setup dotfiles and SSH keys
  hosts: localhost
  become: no

  vars:
    dotfiles_repo: "https://github.com/yaustn/dotfiles.git"
    dotfiles_dest: "{{ ansible_env.HOME }}/github.com/dotfiles"
    ssh_dir: "{{ ansible_env.HOME }}/.ssh"
    ssh_files: "{{ dotfiles_dest }}/ansible/ssh_files.yml"

  tasks:
    - name: Clone/Pull dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dest }}"
        update: yes
        version: master 
      ignore_errors: yes
      tags:
        - dotfiles

    - name: Ensure .ssh directory exists
      become_user: root
      file:
        path: "{{ ssh_dir }}"
        state: directory
        mode: '0700'
      tags:
        - ssh
        - dotfiles

    - name: Decrypt SSH keys file
      ansible.builtin.include_vars:
        file: "{{ ssh_files }}"
        name: ssh_keys
      no_log: true  
      tags:
        - ssh
        - dotfiles

    - name: Copy SSH keys
      copy:
        content: "{{ lookup('file', item.content_file) }}"
        dest: "{{ ssh_dir }}/{{ item.filename }}"
        mode: "{{ item.mode | default('0600') }}"
      loop: "{{ ssh_keys.files }}"
      no_log: true
      tags:
        - ssh
        - dotfiles

    - name: Set authorized ssh key from file
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "{{ ansible_env.HOME }}/.ssh/*.pub"
      tags:
        - ssh
        - dotfiles

    - name: Copy Git configuration files to home directory
      copy:
        src: "{{ dotfiles_dest }}/git/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        mode: '0644'
      loop:
        - gitconfig
        - gitignore
      tags:
        - git
        - dotfiles