return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		main = "nvim-treesitter",
		opts = {
			ensure_installed = {
				"go",
				"python",
				"bash",
				"json",
				"javascript",
				"typescript",
				"c",
				"diff",
				"html",
				"scss",
				"css",
				"lua",
				"luadoc",
				"markdown",
				"markdown_inline",
				"regex",
				"query",
				"vim",
				"vimdoc",
			},
			auto_install = true,
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = { "ruby" },
			},
			indent = { enable = true, disable = { "ruby" } },
		},
	},
}
