#!/bin/bash

export PROJECTS_DIR="$HOME/projects"
export DOTFILES_DIR="$PROJECTS_DIR/dotfiles"
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/.cargo/bin

# start ssh-agent
eval "$(ssh-agent -s)"
if [ -f ~/.ssh/id_rsa ]; then
    ssh-add -k ~/.ssh/id_rsa
else
    ssh-keygen -t rsa -b 4096 -C "yaustn@pm.me"
    ssh-add -k ~/.ssh/id_rsa
fi

# load aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# load functions
if [ -f ~/.bash_fns ]; then
    . ~/.bash_fns
fi

# load dircolors
if [ -f ~/.dircolors ]; then
    . ~/.dircolors
fi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

RED=$(tput setaf 1)
ORANGE=$(tput setaf 3)
LIGHT_GREEN=$(tput setaf 2)
LIGHT_BLUE=$(tput setaf 12)
CYAN=$(tput setaf 14)
PEACH=$(tput setaf 15)
BOLD=$(tput bold)
RESET=$(tput sgr0) # WHITE

PS1="[\[${RED}\]\A\[${RESET}\] \[${ORANGE}\]\u\[${LIGHT_GREEN}\]@\[${CYAN}\]\h\[${LIGHT_BLUE}\]:\[${LIGHT_BLUE}\]\w\[${RESET}\]]\[${PEACH}\]\$(git_branch)\[${RESET}\] $ "

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Clean-up history files from home directory
if [ -f ~/.kpcli-history ]; then
  rm ~/.kpcli-history
fi

if [ -f ~/.sudo_as_admin_successful ]; then
  rm ~/.sudo_as_admin_successful
fi

. $HOME/bin/z

cd ~
cal -A 2

