# Aliases for system
alias suspend='sudo pm-suspend'

alias la='exa -laT --level=1 --group-directories-first'
alias ls='exa -lT --level=1 --group-directories-first'
alias ls2='exa -laT --level=2 --group-directories-first'
alias grep='grep --color=auto'

# Aliases for navigation
alias cddotfiles='cd ~/projects/dotfiles'
#alias cddesktop='cd /mnt/c/Users/anooi/Desktop'
#alias cddocuments='cd /mnt/c/Users/anooi/Documents'
#alias cddownloads='cd /mnt/c/Users/anooi/Downloads'

# Aliases for git
alias gl='git log --graph --decorate --abbrev-commit'
alias gs='git status --show-stash'

# Aliases for kpcli
alias kp="kpcli --kdb=/home/ahyoo/.kdb/ahyoo.kdbx"
alias kpmaster="kpcli --kdb=/home/ahyoo/.kdb/master.kdbx"

# Aliases for top
alias top="htop"
alias du="ncdu"

# Aliases for firefox
alias ff='nohup firefox &>/dev/null &'

# Battery
alias power="upower -i $(upower -e | grep '/battery') | grep --color=never -E 'state|to\ full|to\ empty|percentage'"
